name: Assert version is incremented for repositories containing a package.xml file with a "version" tag

on:
  workflow_call:

jobs:
  check-version:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/umroboticsteam/umrt-apt-image:latest

    steps:
      - name: Checkout pr branch
        uses: actions/checkout@v4
        with:
          path: ./pr

      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          path: ./base
          ref: main

      - name: Extract version numbers
        working-directory: .
        id: extract-versions
        run: |
          echo "PR_PKG_VERSION=$(xml_grep --text_only 'package/version' pr/package.xml)" >> "$GITHUB_ENV"
          echo "BASE_PKG_VERSION=$(xml_grep --text_only 'package/version' base/package.xml)" >> "$GITHUB_ENV"
        shell: bash

      - name: Compare semantic versions
        uses: aleoyakas/check-semver-increased-action@v1
        id: check-version
        with:
          current-version: ${{ env.PR_PKG_VERSION }}
          previous-version: ${{ env.BASE_PKG_VERSION }}

      - name: Validated?
        if: steps.check-version.outputs.is-version-increased != 'true'
        run: |
          echo "::error::Version is not incremented, $PR_PKG_VERSION is not greater than $BASE_PKG_VERSION"
          exit 1
        env:
          PR_PKG_VERSION: ${{ steps.extract-versions.outputs.PR_PKG_VERSION }}
          BASE_PKG_VERSION: ${{ steps.extract-versions.outputs.BASE_PKG_VERSION }}